### PR TITLE
Updated the README.md with @hello-pangea/dnd

### LINKED ISSUE #19: Missing dependecies hello-pangea/dnd
I've just finished porting the asseinfo branch with thiis branch. Good job guys. But when I tried to run the project after instaled it using yarn, Vite could not compile it, saying the https://github.com/hello-pangea/dnd  is missing. After installing locally it solved the issue. But could we add as dependencie for this project?

### PR DESCRIPTION
**Pull request by DrZanuff**
Updated the README.md with references to install @hello-pangea/dnd

## Description

Even with the list of dependencies containing @hello-pangea/dnd, I think it would be interesting to contain this information in the project description;

## How Has This Been Tested?

This is just an update on the README.md

### CODE REVIEW

**Comment by christopher-caldwell** [comment]
Something's off with your githistory here. There's 44 files being "changed". 

I'm not opposed to putting a blurb on the readme. If you get the history sorted, the readme addition looks good to me.

**Comment by DrZanuff** [comment]
@christopher-caldwell sorry, created the PR via Github web interface, I think this must be a bug. I'll create a PR forking the project.

**Comment by samuelbailor** [comment]
What is the status of this README update? I still see no mention of installing @hello-pangea/dnd as a dependency, even though I see it listed as a peer in your package.json.

**Comment by christopher-caldwell** [comment]
@DrZanuff said he was going to fix this git issue, but it's been awhile. I'll close this PR and just update the readme.

**Comment by christopher-caldwell** [comment]
This has been fixed by [this](https://github.com/christopher-caldwell/react-kanban/pull/22) PR.

**Pull request closed without merging**
